package com.lms.system.customer.account.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.lms.system.customer.account.enums.AccountType;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@Schema(name = "Accounts",description = "Holds accounts information of a customer")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class AccountsDTO {

    @Schema(description = "Autogenerated account number")
    private Long accountNumber;
    @Schema(description = "Customer's account type", example = "SAVINGS")
    private AccountType accountType;
    @Schema(description = "Customer's Branch name", example = "TRM Bank")
    private String branchName;
    @Schema(description = "Customer's home address")
    private String branchAddress;
}
